(() => {
  'use strict';
  const catalog = window.IDEA_CATALOG;
  const synthesis = window.IDEA_SYNTHESIS;
  const translations = window.IDEA_TRANSLATIONS;
  const ui = window.FIELDNOTES_UI;
  const assessments = window.IDEA_SCORES;
  const rubric = assessments.rubric;
  const $ = (s, root=document) => root.querySelector(s);
  const $$ = (s, root=document) => [...root.querySelectorAll(s)];
  const escape = value => String(value ?? '').replace(/[&<>"']/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const ideas = new Map(catalog.ideas.map(i=>[i.id,i]));
  const themes = new Map(catalog.themes.map(i=>[i.id,i]));
  const featured = new Map(synthesis.featured.map(i=>[i.id,i]));
  const criteria = new Map(rubric.criteria.map(c=>[c.key,c]));
  let lang='zh';
  try { if(localStorage.getItem('fieldnotes-language-v1')==='en')lang='en'; } catch {}
  const urlLang=new URLSearchParams(location.search).get('lang');
  if(['en','zh'].includes(urlLang))lang=urlLang;
  const t=(key,args={})=>{let value=ui[key]?.[lang==='zh'?1:0] ?? key;for(const [k,v] of Object.entries(args))value=value.replaceAll('{'+k+'}',String(v));return value;};
  const field=(idea,key)=>lang==='zh'?(translations.ideas[idea.id]?.[key] ?? idea[key]):idea[key];
  const title=idea=>lang==='zh'?(translations.shared.featured[idea.id]?.display_title || field(idea,'title')):(featured.get(idea.id)?.display_title || idea.title);
  const themeTitle=id=>id==='all'?t('allTopics'):(lang==='zh'?translations.shared.themes[id]:themes.get(id).title);
  const criterionLabel=key=>key==='total'?t('total'):criteria.get(key).label[lang];
  const assessment=idea=>assessments.ideas[idea.id];
  const validURL=value=>{try{const u=new URL(value);return u.protocol==='https:'?u.href:'';}catch{return '';}};
  const chip=idea=>`<span class="status-chip ${idea.readiness}">${t(idea.readiness)}</span>`;
  const tone=idea=>`--tint:${palette[idea.theme][0]};--tone:${palette[idea.theme][1]}`;
    const palette = {
    agents:['#e6ecdf','#5a7250'], teams:['#eae6f0','#7c6793'], scientist:['#e4ebee','#517f8c'],
    ising:['#f0e6d8','#9b7a4b'], physical:['#eee3df','#a07165'], life:['#e5ecdc','#6b8350'],
    networks:['#e0ebe5','#598371'], environment:['#e9ebd8','#7a844b'], data:['#e9e7de','#81765d'],
    learning:['#ede3e9','#9b6e8c'], sound:['#f0e8d6','#a58a48'], puzzles:['#e5e6ed','#737c9d']
  };
  const paths = {
    all:'M3 3h6v6H3zM15 3h6v6h-6zM3 15h6v6H3zM15 15h6v6h-6z',
    agents:'M5 7h14v12H5zM9 11h.1M15 11h.1M9 15h6M12 3v4M2 10v5M22 10v5',
    teams:'M9 7a3 3 0 1 1-6 0 3 3 0 0 1 6 0M21 7a3 3 0 1 1-6 0 3 3 0 0 1 6 0M2 21v-5a4 4 0 0 1 8 0v5M14 21v-5a4 4 0 0 1 8 0v5M10 17h4',
    scientist:'M8 3h8M10 3v7L4 20h16l-6-10V3M7 15h10',
    ising:'M5 3v18M12 3v18M19 3v18M3 5h18M3 12h18M3 19h18',
    physical:'M2 12c4-15 6 15 10 0s6 15 10 0',
    life:'M12 21v-9M12 16C3 15 2 11 3 6c6 0 9 3 9 10M12 12c0-7 4-9 9-9 0 6-3 9-9 9',
    networks:'M5 5l14 2-7 13L5 5M5 5l-2 13 9 2M19 7l3 12-10 1',
    environment:'M3 20l6-14 4 9 3-5 5 10H3M16 4h.1',
    data:'M4 3h16v18H4zM8 7h8M8 11h8M8 15h3M14 16l2 2 5-6',
    learning:'M3 12h5l4-8 4 16 3-8h3',
    sound:'M3 10v4M7 6v12M11 3v18M15 7v10M19 5v14M23 10v4',
    puzzles:'M4 4h6c-2 6 6 6 4 0h6v6c-6-2-6 6 0 4v6h-6c2-6-6-6-4 0H4v-6c6 2 6-6 0-4V4'
  };
  const icon = name => `<svg class="topic-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[name] || paths.all}"/></svg>`;
  const bookmark = '<svg viewBox="0 0 18 20" aria-hidden="true"><path d="M4 2h10v16l-5-3-5 3z"/></svg>';
  function miniArt(theme) {
    let art;
    if (['ising','puzzles'].includes(theme)) {
      art = Array.from({length:16},(_,i) => {const x=27+(i%4)*18,y=10+Math.floor(i/4)*18;return `<rect x="${x}" y="${y}" width="15" height="15" rx="2" class="${[0,3,5,6,10,12,15].includes(i)?'filled':''}"/><path d="M${x+4} ${y+7.5}h7${i%3 ? `m-3.5-3.5v7` : ''}"/>`;}).join('');
    } else if (['sound','physical'].includes(theme)) {
      art = '<path d="M5 45h115" stroke-dasharray="2 4"/>' + Array.from({length:17},(_,i)=>{const h=8+Math.abs(Math.sin(i*.62))*46;return `<path d="M${13+i*6} ${45-h/2}v${h}" stroke-width="2.5"/>`;}).join('');
    } else if (['life','environment'].includes(theme)) {
      art = '<ellipse cx="64" cy="47" rx="43" ry="27" stroke-dasharray="2 4"/>' + [[38,38,9],[58,26,6],[73,41,11],[50,59,12],[84,61,5],[88,29,4],[31,65,4],[73,73,3],[102,47,3]].map(([x,y,r])=>`<circle cx="${x}" cy="${y}" r="${r}" class="filled"/><circle cx="${x}" cy="${y}" r="${r}"/><circle cx="${x}" cy="${y}" r="2" class="dot"/>`).join('');
    } else if (theme === 'scientist') {
      art = '<path d="M17 10v63h96M25 64c12-1 9-39 27-25s12 20 23 0 20-18 31-23"/><path d="M25 68c30-8 42-15 80-49" stroke-dasharray="3 4"/><circle cx="52" cy="39" r="4" class="dot"/><circle cx="86" cy="23" r="4" class="dot"/><path d="M104 6v10m-5-5h10"/>';
    } else if (theme === 'data') {
      art = '<rect x="19" y="13" width="53" height="58" rx="3"/><rect x="53" y="23" width="53" height="58" rx="3" class="filled"/><path d="M29 27h30M29 37h30M29 47h12M63 37h30M63 47h30M63 57h12M81 67l7 6 14-19"/><path d="M6 20h6m-3-3v6"/>';
    } else {
      const nodes = [[26,21],[65,14],[101,29],[92,67],[48,73],[19,52],[58,44]];
      art = '<path d="M26 21L65 14 101 29 92 67 48 73 19 52 26 21 58 44 65 14M58 44l43-15M58 44l34 23M58 44L48 73M58 44L19 52"/>' + nodes.map(([x,y],i)=>`<circle cx="${x}" cy="${y}" r="${i===6?11:6}" fill="${palette[theme][0]}"/><circle cx="${x}" cy="${y}" r="${i===6?5:2}" class="dot"/>`).join('');
    }
    return `<svg class="mini-art" viewBox="0 0 130 90" aria-hidden="true">${art}</svg>`;
  }

  const ordered=synthesis.featured.map(i=>ideas.get(i.id));
  const sourceQueues=['astra','fable'].map(source=>{const queues=catalog.themes.map(theme=>catalog.ideas.filter(i=>i.source===source&&i.theme===theme.id&&!featured.has(i.id)));const result=[];while(queues.some(q=>q.length))for(const queue of queues)if(queue.length)result.push(queue.shift());return result;});
  while(sourceQueues.some(q=>q.length))for(const queue of sourceQueues)if(queue.length)ordered.push(queue.shift());
  const discoveryIndex=new Map(ordered.map((idea,index)=>[idea.id,index]));
  const state={theme:'all',view:'all',readiness:'all',track:'all',query:'',limit:12,sort:'discovery',order:'desc'};
  const searchIndex=new Map(catalog.ideas.map(i=>[i.id,[i.id,i.sourceId,i.title,i.hook,i.question,i.firstMonth,i.originalDirection,themes.get(i.theme).title,...i.papers.map(p=>p.title),...Object.values(translations.ideas[i.id]).filter(v=>typeof v==='string'),...translations.ideas[i.id].papers.flatMap(p=>[p.title,p.supports]),translations.shared.themes[i.theme],translations.shared.featured[i.id]?.display_title||''].join(' ').normalize('NFKC').toLowerCase()]));
  const storageKey='fieldnotes-shortlist-v1';
  let saved={},rawSaved={},storageOK=true,toastTimer,detailReturnFocus,detailReturnTarget=null,detailId=null;
  const comparisons=new Set();
  function readStore(){try{const value=JSON.parse(localStorage.getItem(storageKey)||'{}');return value&&typeof value==='object'&&!Array.isArray(value)?value:{};}catch{storageOK=false;return rawSaved;}}
  function loadSaved(raw){rawSaved=raw;saved={};for(const [id,v] of Object.entries(raw))if(ideas.has(id)&&v&&typeof v==='object')saved[id]={interest:['curious','try','favorite'].includes(v.interest)?v.interest:'curious',note:typeof v.note==='string'?v.note.slice(0,3000):''};for(const id of comparisons)if(!saved[id])comparisons.delete(id);}
  function updateStorageUI(){$('#saved-count').textContent=Object.keys(saved).length;$$('[data-storage-note]').forEach(el=>el.textContent=storageNote());}
  function changeSaved(id,patch){const raw=readStore();if(patch===null)delete raw[id];else raw[id]={...(raw[id]&&typeof raw[id]==='object'?raw[id]:{interest:'curious',note:''}),...patch};loadSaved(raw);try{localStorage.setItem(storageKey,JSON.stringify(raw));storageOK=true;}catch{storageOK=false;}updateStorageUI();}
  function storageNote(){return t(storageOK?'storageNote':'storageFailed');}
  function toast(text){clearTimeout(toastTimer);$('#toast').textContent=text;$('#toast').classList.add('visible');toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),2800);}
  function renderStatic(){
    document.documentElement.lang=lang==='zh'?'zh-CN':'en';document.title=t('pageTitle');$('.brand').setAttribute('aria-label',t('pageTitle'));
    const pairs={'.skip-link':'skip','.brand-sub':'labName','.nav-explore':'explore','.nav-guide':'choose','.shortlist-label':'shortlist','.hero-eyebrow-copy':'heroEyebrow','.hero-copy>p':'heroDescription','.hero-cta-copy':'findStart','.art-top>span:first-child':'artTitle','.art-top>span:last-child':'figure','.art-bottom>span:first-child':'artCaption','.strip-between':'between','.collection-about':'about','.sidebar-label':'followCuriosity','.sidebar-note>p':'sidebarDescription','.sidebar-note .text-button':'quickGuide','.section-heading .eyebrow':'collectionEyebrow','#collection-title':'collectionTitle','.surprise-button':'surprise','.search-label':'search','.readiness-label':'startingPoint','.all-tab-label':'allIdeas','.featured-tab-label':'startHere','.track-label':'interestFilter','.sort-label':'sortBy','#score-guide-button':'scoringGuide','#clear-filters':'clear','#empty-state h3':'emptyTitle','#empty-state p':'emptyDescription','#empty-state button':'exploreAll','#load-more':'more','.closing-note .eyebrow':'closingEyebrow','.closing-note p':'closingDescription','.closing-note .text-button':'makeOwn','.footer-lab':'labNameNormal','.footer-preview':'preview','footer .plain-button':'sources','.noscript':'noscript'};
    for(const [selector,key] of Object.entries(pairs)){const el=$(selector);if(el)el.textContent=t(key);}
    for(const [selector,key] of [['#hero-title','heroTitle'],['.hero-note','heroNote'],['.sidebar-note h3','sidebarTitle'],['.closing-note h2','closingTitle']])$(selector).innerHTML=t(key);
    $('#strip-ideas').innerHTML=`<strong>${catalog.ideas.length}</strong> ${t('ideaCount',{n:''}).trim()}`;
    $('#strip-paths').innerHTML=`<strong>${catalog.themes.length}</strong> ${t('pathCount',{n:''}).trim()}`;
    $('.all-tab-count').textContent=catalog.ideas.length;
    $('#search').placeholder=t('searchPlaceholder');$('#search').setAttribute('aria-label',t('search'));
    $('nav').setAttribute('aria-label',t('navigation'));$('#topic-list').setAttribute('aria-label',t('topicLabel'));$('.view-tabs').setAttribute('aria-label',t('view'));$('.language-switch').setAttribute('aria-label',t('language'));
    $$('.language-button').forEach(b=>{b.setAttribute('aria-pressed',b.dataset.lang===lang);b.classList.toggle('active',b.dataset.lang===lang);});
    $('#readiness-filter').innerHTML=['all','start','mentor','rework'].map(v=>`<option value="${v}">${t(v==='all'?'anyStarting':v)}</option>`).join('');$('#readiness-filter').value=state.readiness;
    $('#track-filter').innerHTML=['all','ai','physics','open'].map(v=>`<option value="${v}">${t(v==='all'?'allInterests':v)}</option>`).join('');$('#track-filter').value=state.track;
    $('#sort-by').innerHTML=`<option value="discovery">${t('discoveryOrder')}</option><option value="total">${t('total')}</option>`+rubric.criteria.map(c=>`<option value="${c.key}">${escape(c.label[lang])}</option>`).join('');$('#sort-by').value=state.sort;updateSortOrder();
    const words=$$('.discovery-map text');['wonder','experimentWord','discover'].forEach((key,n)=>{words[n].textContent=t(key);words[n].setAttribute('x',(lang==='zh'?[45,247,451]:[28,226,430])[n]);});
  }
  function updateSortOrder(){$('#sort-order').textContent=t(state.order==='desc'?'descending':'ascending');$('#sort-order').disabled=state.sort==='discovery';$('#sort-order').setAttribute('aria-label',t(state.order==='desc'?'descending':'ascending'));}
  function changeLanguage(next){if(!['en','zh'].includes(next)||next===lang)return;const activeDialog=document.activeElement?.closest('dialog')?.id;const detailScroll=$('#detail-dialog').scrollTop,scoreWasOpen=!!$('#score-details')?.open;lang=next;try{localStorage.setItem('fieldnotes-language-v1',lang);}catch{}const url=new URL(location.href);url.searchParams.set('lang',lang);history.replaceState(null,'',url);renderStatic();render();if($('#detail-dialog').open&&detailId){detail(detailId,false);$('#score-details').open=scoreWasOpen;$('#detail-dialog').scrollTop=detailScroll;}if($('#shortlist-dialog').open)renderShortlist();if($('#compare-dialog').open)compare();if($('#info-dialog').open)info($('#info-dialog').dataset.kind);if(activeDialog)$(`#${activeDialog} [data-lang="${lang}"]`)?.focus({preventScroll:true});}
  function renderTopics(){const scroll=$('#topic-list').scrollLeft;$('#topic-list').innerHTML=[{id:'all'},...catalog.themes].map(theme=>`<button class="topic-button ${state.theme===theme.id?'active':''}" data-theme="${theme.id}" aria-pressed="${state.theme===theme.id}">${icon(theme.id)}<span>${escape(themeTitle(theme.id))}</span><span class="topic-count">${theme.id==='all'?catalog.ideas.length:catalog.ideas.filter(i=>i.theme===theme.id).length}</span></button>`).join('');$('#topic-list').scrollLeft=scroll;}
  function filtered(){
    const terms=state.query.normalize('NFKC').trim().toLowerCase().split(/\s+/).filter(Boolean);
    const out=ordered.filter(i=>(state.theme==='all'||i.theme===state.theme)&&(state.view==='all'||featured.has(i.id))&&(state.readiness==='all'||i.readiness===state.readiness)&&(state.track==='all'||i.tracks.includes(state.track))&&terms.every(term=>searchIndex.get(i.id).includes(term)));
    if(state.sort!=='discovery'){const value=i=>state.sort==='total'?assessment(i).total:assessment(i).scores[state.sort];out.sort((a,b)=>(state.order==='desc'?value(b)-value(a):value(a)-value(b))||(state.sort==='total'?0:assessment(b).total-assessment(a).total)||discoveryIndex.get(a.id)-discoveryIndex.get(b.id)||a.id.localeCompare(b.id,'en'));}
    return out;
  }
  function card(idea){
    const score=assessment(idea);const selected=state.sort!=='discovery'&&state.sort!=='total'?`<span class="component-sort-value">${escape(criterionLabel(state.sort))} ${score.scores[state.sort]}/5</span>`:'';
    return `<article class="idea-card" style="${tone(idea)}" data-idea="${idea.id}"><div class="card-art"><span class="card-code">${idea.id}</span>${miniArt(idea.theme)}<button class="save-button ${saved[idea.id]?'saved':''}" data-save="${idea.id}" aria-label="${escape(t(saved[idea.id]?'removeLabel':'saveLabel',{title:title(idea)}))}" aria-pressed="${!!saved[idea.id]}">${bookmark}</button><button class="score-pill" data-open="${idea.id}" data-jump="score" aria-label="${escape(title(idea))} · ${t('scoreLabel')} ${score.total}/100">${t('total')} <strong>${score.total}</strong><span>/100</span></button></div><div class="card-content"><div class="card-label">${escape(themeTitle(idea.theme))}</div><h3 class="card-title"><button data-open="${idea.id}">${escape(title(idea))}</button></h3><p class="card-pitch">${escape(lang==='en'?(featured.get(idea.id)?.why_featured||idea.hook||idea.question):(field(idea,'hook')||field(idea,'question')))}</p><div class="card-meta">${chip(idea)}<span class="track-chip">${idea.tracks.map(v=>t(v)).join(' · ')}</span>${selected}</div><div class="card-bottom"><span>${t('paperCount',{n:idea.papers.length})}</span><button class="card-open" data-open="${idea.id}" aria-label="${escape(t('exploreLabel',{title:title(idea)}))}">${t('exploreIdea')} <b aria-hidden="true">↗</b></button></div></div></article>`;
  }
  function render(){const results=filtered();$('#idea-grid').innerHTML=results.slice(0,state.limit).map(card).join('');const subtitle=state.sort==='discovery'?t(state.view==='featured'?'balanced':'roomToGrow'):t('sortedNote',{criterion:criterionLabel(state.sort),order:t(state.order==='desc'?'highLow':'lowHigh')});$('#result-count').textContent=t('results',{n:results.length})+' · '+subtitle;$('#empty-state').hidden=!!results.length;$('#load-more').hidden=results.length<=state.limit;$('#shown-count').textContent=results.length?t('shown',{shown:Math.min(state.limit,results.length),total:results.length}):'';$('#clear-filters').hidden=state.theme==='all'&&state.view==='all'&&state.readiness==='all'&&state.track==='all'&&!state.query;$$('.view-tab').forEach(b=>{b.classList.toggle('active',b.dataset.view===state.view);b.setAttribute('aria-pressed',b.dataset.view===state.view);});renderTopics();}
  function reset(){Object.assign(state,{theme:'all',view:'all',readiness:'all',track:'all',query:'',limit:12});$('#search').value='';$('#readiness-filter').value='all';$('#track-filter').value='all';render();}
  function updateSaveButtons(id){$$(`[data-save="${id}"]`).forEach(b=>{b.classList.toggle('saved',!!saved[id]);b.setAttribute('aria-pressed',!!saved[id]);if(b.classList.contains('save-button'))b.setAttribute('aria-label',t(saved[id]?'removeLabel':'saveLabel',{title:title(ideas.get(id))}));else b.textContent=t(saved[id]?'savedButton':'saveButton');});}
  function toggleSave(id){if(!ideas.has(id))return;const removing=!!saved[id];changeSaved(id,removing?null:{interest:'curious',note:''});comparisons.delete(id);toast(t(storageOK?(removing?'removedToast':'savedToast'):'storageWarning'));updateSaveButtons(id);if($('#shortlist-dialog').open){renderShortlist();$('#shortlist-title').focus({preventScroll:true});}}
  function openDialog(dialog){if(!dialog.open)dialog.showModal();dialog.scrollTop=0;}
  function dialogTop(label,id,closeKey){return `<div class="dialog-top"><span>${escape(label)}</span><div class="dialog-tools"><div class="language-switch" role="group" aria-label="${t('language')}">${['zh','en'].map(v=>`<button class="language-button ${lang===v?'active':''}" data-lang="${v}" lang="${v==='zh'?'zh-CN':'en'}" aria-pressed="${lang===v}">${v==='zh'?'中文':'EN'}</button>`).join('')}</div><button class="close-button" data-close="${id}" aria-label="${t(closeKey)}">×</button></div></div>`;}
  function related(idea){const groups=synthesis.overlap_clusters.filter(g=>g.members.includes(idea.id));return{groups,ids:[...new Set(groups.flatMap(g=>g.members))].filter(id=>id!==idea.id&&ideas.has(id))};}
  function scorePanel(idea){const a=assessment(idea);return `<details id="score-details" class="score-details"><summary><span>${t('scoreLabel')} <strong>${a.total}/100</strong></span><span>${t('scoreDetails')} ↓</span></summary><div class="score-details-body"><p class="score-summary">${escape(a.summary[lang])}</p><p class="storage-note">${t('scoreDepth')}</p><div class="score-component-list">${rubric.criteria.map(c=>`<div class="score-component"><div><strong>${escape(c.label[lang])}</strong><span>${c.weight}%</span></div><meter min="0" max="5" value="${a.scores[c.key]}" aria-label="${escape(c.label[lang])}">${a.scores[c.key]}/5</meter><span class="component-number">${a.scores[c.key]}/5</span><p>${escape(c.description[lang])}</p><details class="score-evidence"><summary>${t('evidence')}</summary><p>${escape(lang==='zh'?translations.evidence[idea.id][c.key]:a.evidence[c.key].reason)}</p></details></div>`).join('')}</div><p class="review-note">${escape(a.nextCheck[lang])}</p><p class="storage-note">${t('scoreVersion')}：${rubric.version} · ${t('assessor',{id:a.assessor==='first'?1:2})} · ${t('scoreNote')}</p><button class="text-button" data-action="scoring">${t('scoringGuide')} ↗</button></div></details>`;}
  function detail(id,pushHash=true,jumpScore=false){
    const idea=ideas.get(id);if(!idea)return;const wasOpen=$('#detail-dialog').open;if(!wasOpen){detailReturnFocus=document.activeElement;detailReturnTarget={id:detailReturnFocus?.dataset?.open,action:detailReturnFocus?.dataset?.action};}detailId=id;
    const relation=related(idea);const extra=synthesis.implementation_caveats.flatMap((c,n)=>c.ids.includes(id)?[lang==='zh'?translations.shared.caveats[n]:c.note]:[]);
    const first=featured.get(id);const firstStep=lang==='zh'?translations.shared.featured[id]?.first_step:first?.first_step;
    const section=(key,content,cls='')=>content?`<section class="detail-section ${cls}"><h3>${t(key)}</h3><p>${escape(content)}</p></section>`:'';
    $('#detail-content').innerHTML=`${dialogTop(id+' · '+themeTitle(idea.theme),'detail-dialog','closeDetails')}<div class="detail-header" style="${tone(idea)}"><div class="eyebrow">${t('questionEyebrow')}</div><h2 id="detail-title" tabindex="-1">${escape(title(idea))}</h2><p>${escape(field(idea,'question'))}</p><div class="detail-actions"><button class="primary-button" data-save="${id}" aria-pressed="${!!saved[id]}">${t(saved[id]?'savedButton':'saveButton')}</button>${chip(idea)}</div></div><div class="detail-body">${scorePanel(idea)}${firstStep?section('firstStep',firstStep,'first-step'):''}${section('firstMonth',field(idea,'firstMonth'),firstStep?'':'first-step')}${section('experiment',field(idea,'experiment'))}<div class="detail-columns">${section('baseline',field(idea,'baseline'))}${section('resources',field(idea,'resources'))}</div>${section('publicationPath',field(idea,'publicationPath'))}${section('risk',field(idea,'risk'))}${section('pivot',field(idea,'pivot'))}<div class="review-note"><strong>${t('beforeBegin')}</strong><br>${escape(field(idea,'readinessReason'))}${extra.map(note=>`<p>${escape(note)}</p>`).join('')}<br>${t('conditional')}</div><section class="detail-section" style="margin-top:25px"><h3>${t('readPapers')}</h3>${idea.papers.map(p=>{const local=lang==='zh'?translations.ideas[id].papers.find(x=>x.id===p.id):p;const url=validURL(p.url);return `<a class="paper-link" href="${escape(url)}" target="_blank" rel="noopener noreferrer"><strong>${escape(local.title)} ↗</strong>${lang==='zh'?`<span class="original-paper-title" lang="en">${escape(p.title)}</span>`:''}<span>${escape(local.supports)}</span><span class="paper-id">${escape(p.id)} · ${escape(p.year||'')} · ${t('readingDepth')}：${escape(lang==='zh'?translations.shared.readingDepth[p.readDepth]:p.readDepth)}</span></a>`;}).join('')}<p class="storage-note">${t('referenceNote')}</p></section>${relation.ids.length?`<section class="detail-section"><h3>${t('related')}</h3><p class="storage-note">${t('relatedNote')}</p><div class="related-links">${relation.ids.slice(0,7).map(other=>`<button class="related-button" data-open="${other}">${escape(title(ideas.get(other)))} ↗</button>`).join('')}</div><details class="source-details" style="margin-top:12px"><summary>${t('connections')}</summary>${relation.groups.map(g=>{const text=lang==='zh'?translations.shared.clusters[g.id]:g;return `<p><strong>${escape(text.label)}</strong><br>${escape(text.explanation)}</p>`;}).join('')}</details></section>`:''}<details class="source-details"><summary>${t('original')}</summary><p><strong>${idea.source==='astra'?'Astra':'Fable'} · ${idea.sourceId}</strong><br><span lang="en">${escape(idea.originalAssessment?.finalRanking?.title||idea.displayCorrection?.previousFields?.title||idea.title)}</span></p><p>${escape(t('sourceScore',{source:idea.source==='astra'?'Astra':'Fable',value:idea.sourceScore.value,max:idea.sourceScore.max,rank:idea.sourceScore.rank}))}</p><p>${t('originalNote')}</p></details></div>`;
    $('#detail-dialog').setAttribute('aria-labelledby','detail-title');openDialog($('#detail-dialog'));if(wasOpen)$('#detail-title').focus({preventScroll:true});if(pushHash)history.replaceState(null,'',`#idea=${encodeURIComponent(id)}`);if(jumpScore){$('#score-details').open=true;$('#score-details').scrollIntoView({block:'start'});}
  }
  function closeDetail(){detailId=null;if(location.hash.startsWith('#idea='))history.replaceState(null,'','#collection');if(detailReturnFocus?.isConnected)detailReturnFocus.focus({preventScroll:true});else if($('#shortlist-dialog').open)$('#shortlist-title').focus({preventScroll:true});else if(detailReturnTarget?.id)$(`.card-title [data-open="${detailReturnTarget.id}"]`)?.focus({preventScroll:true});else if(detailReturnTarget?.action)$(`[data-action="${detailReturnTarget.action}"]`)?.focus({preventScroll:true});}
  function renderShortlist(){const entries=Object.entries(saved);const scroll=$('#shortlist-dialog').scrollTop;$('#shortlist-content').innerHTML=`${dialogTop(t('shortlistEyebrow'),'shortlist-dialog','closeShortlist')}<div class="shortlist-body"><div class="shortlist-intro"><h2 id="shortlist-title" tabindex="-1">${t('shortlistTitle')}</h2><p>${entries.length?t('shortlistIntro',{n:entries.length}):t('shortlistEmpty')}</p></div><div class="shortlist-tools"><button class="primary-button" data-action="export" ${entries.length?'':'disabled'}>${t('export')}</button><button id="compare-button" class="secondary-button" data-action="compare" ${comparisons.size>=2?'':'disabled'}>${t('compareButton',{n:comparisons.size})}</button></div>${entries.map(([id,item])=>{const idea=ideas.get(id);return `<article class="saved-item"><div class="saved-heading"><div><span class="saved-topic">${escape(themeTitle(idea.theme))} · ${id}</span><h3><button data-open="${id}">${escape(title(idea))}</button></h3>${chip(idea)} <span class="saved-score">${t('total')} ${assessment(idea).total}/100</span></div><button class="remove-button" data-remove="${id}" aria-label="${escape(t('removeLabel',{title:title(idea)}))}">${t('remove')}</button></div><div class="saved-controls"><label class="interest-label">${t('myInterest')} <select data-interest="${id}">${['curious','try','favorite'].map(v=>`<option value="${v}" ${item.interest===v?'selected':''}>${t(v)}</option>`).join('')}</select></label><label class="compare-check"><input type="checkbox" data-compare="${id}" ${comparisons.has(id)?'checked':''}>${t('compareThis')}</label></div><label class="note-label">${t('noteQuestion')}<textarea data-note="${id}" maxlength="3000" placeholder="${t('notePlaceholder')}">${escape(item.note)}</textarea></label></article>`;}).join('')}<p class="storage-note" data-storage-note>${storageNote()}</p>${!entries.length?`<button class="secondary-button" data-close="shortlist-dialog">${t('backExplore')}</button>`:''}</div>`;$('#shortlist-dialog').setAttribute('aria-labelledby','shortlist-title');$('#shortlist-dialog').scrollTop=scroll;}
  function download(name,content,type){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  function exportShortlist(){const parts=['# '+t('exportTitle'),t('exportDate',{date:new Date().toISOString().slice(0,10)}),t('exportDisclaimer')];Object.entries(saved).forEach(([id,item])=>{const idea=ideas.get(id);const a=assessment(idea);parts.push(`## ${title(idea)} (${id})`,`${t('topic')}: ${themeTitle(idea.theme)}\n${t('myInterest')}: ${t(item.interest)}\n${t('startingPoint')}: ${t(idea.readiness)}`,`${t('total')}: ${a.total}/100 (${rubric.version})\n${rubric.criteria.map(c=>`${c.label[lang]}: ${a.scores[c.key]}/5`).join(' · ')}`,`${t('myNotes')}:\n\n${(item.note||t('noNotes')).split('\n').map(line=>'    '+line).join('\n')}`,`${t('question')}: ${field(idea,'question')}`,`${t('firstMonth')}: ${field(idea,'firstMonth')}`,`${t('resources')}: ${field(idea,'resources')}`,`${t('preparation')}: ${field(idea,'readinessReason')}`,`${t('risk')}: ${field(idea,'risk')}`,`${t('originalTitle')}: ${idea.originalAssessment?.finalRanking?.title||idea.displayCorrection?.previousFields?.title||idea.title}`,`${t('papers')}:\n${idea.papers.map(p=>`- ${lang==='zh'?translations.ideas[id].papers.find(x=>x.id===p.id).title+' / ':''}${p.title}: ${p.url}`).join('\n')}`);});download(lang==='zh'?'我的科研意向清单.md':'my-research-shortlist.md',parts.join('\n\n')+'\n','text/markdown;charset=utf-8');toast(t('exported'));}
  function compare(){const selected=[...comparisons].filter(id=>saved[id]).map(id=>ideas.get(id));if(selected.length<2||selected.length>3)return;const rows=[[t('total'),i=>`${assessment(i).total}/100`],...rubric.criteria.map(c=>[c.label[lang],i=>`${assessment(i).scores[c.key]}/5`]),[t('startingPoint'),i=>t(i.readiness)],...['firstMonth','resources','baseline','publicationPath','risk'].map(key=>[t(key),i=>field(i,key)]),[t('preparation'),i=>field(i,'readinessReason')]];$('#compare-content').innerHTML=`${dialogTop(t('compareEyebrow'),'compare-dialog','closeCompare')}<div class="compare-body"><h2 id="compare-title">${t('compareTitle')}</h2><p>${t('compareIntro')}</p><div class="compare-table-wrap" tabindex="0" role="region" aria-label="${t('compareRegion')}"><table class="compare-table"><thead><tr><th scope="col" class="row-label">${t('project')}</th>${selected.map(i=>`<th scope="col">${escape(title(i))}</th>`).join('')}</tr></thead><tbody>${rows.map(([label,get])=>`<tr><th scope="row" class="row-label">${escape(label)}</th>${selected.map(i=>`<td>${escape(get(i))}</td>`).join('')}</tr>`).join('')}</tbody></table></div></div>`;$('#compare-dialog').setAttribute('aria-labelledby','compare-title');openDialog($('#compare-dialog'));}
  function info(which){const guide=which==='guide',scoring=which==='scoring';$('#info-dialog').dataset.kind=which;let body;
    if(guide)body=`<ol class="guide-steps">${[1,2,3,4].map(n=>`<li><strong>${t('guideStep'+n+'Title')}</strong>${t('guideStep'+n)}</li>`).join('')}</ol>${['start','mentor','rework'].map(v=>`<p><span class="status-chip ${v}">${t(v)}</span> ${t(v+'Meaning')}</p>`).join('')}<p>${t('readinessCaveat')}</p>`;
    else if(scoring)body=`<p>${t('scoreIntro')}</p><p class="review-note">${t('scoreFormula')}</p><div class="rubric-list">${rubric.criteria.map(c=>`<details><summary><strong>${escape(c.label[lang])}</strong><span>${c.weight}%</span></summary><p>${escape(c.description[lang])}</p><ol start="0">${Object.values(lang==='zh'?c.anchorsZh:c.anchors).map(x=>`<li>${escape(x)}</li>`).join('')}</ol></details>`).join('')}</div><p>${t('scoreCaveat')}</p><p>${t('calibration')}</p><p>${t('calibrationNumbers',{n:assessments.provenance.calibration.sharedCases.length,d:assessments.provenance.calibration.meanAbsoluteTotalDifference.toFixed(1)})}</p><p>${t('readinessCaveat')}</p><p class="storage-note">${t('scoreVersion')}: ${rubric.version}</p>`;
    else body=['aboutCollections','aboutSelection','aboutScores','aboutLiterature','aboutPrivacy'].map(k=>`<p>${t(k)}</p>`).join('')+`<button class="secondary-button" data-action="catalog-export">${t('downloadCatalog')}</button><p class="storage-note">${t('preview')}</p>`;
    $('#info-content').innerHTML=`${dialogTop(t(scoring?'scoringGuide':guide?'choose':'about'),'info-dialog','closeInfo')}<div class="info-body"><h2 id="info-title">${t(scoring?'scoreTitle':guide?'guideTitle':'aboutTitle')}</h2>${body}</div>`;$('#info-dialog').setAttribute('aria-labelledby','info-title');openDialog($('#info-dialog'));
  }
  document.addEventListener('click',event=>{const b=event.target.closest('button');if(!b)return;if(b.dataset.lang){changeLanguage(b.dataset.lang);return;}if(b.dataset.open){detail(b.dataset.open,true,b.dataset.jump==='score');return;}if(b.dataset.save){toggleSave(b.dataset.save);return;}if(b.dataset.remove){toggleSave(b.dataset.remove);return;}if(b.dataset.close){$('#'+b.dataset.close).close();return;}if(b.dataset.theme){state.theme=b.dataset.theme;state.limit=12;render();$(`[data-theme="${state.theme}"]`).focus({preventScroll:true});return;}if(b.dataset.view){state.view=b.dataset.view;state.limit=12;render();return;}const action=b.dataset.action;if(action==='shortlist'){renderShortlist();openDialog($('#shortlist-dialog'));}if(['guide','about','scoring'].includes(action))info(action);if(action==='reset')reset();if(action==='export')exportShortlist();if(action==='compare')compare();if(action==='catalog-export')download('fieldnotes-bilingual-catalog.json',JSON.stringify({catalog,translations,synthesis,assessments},null,2),'application/json');if(action==='surprise'){const pool=filtered();if(pool.length)detail(pool[Math.floor(Math.random()*pool.length)].id);else toast(t('emptySurprise'));}});
  document.addEventListener('input',event=>{const el=event.target;if(el.id==='search'){state.query=el.value;state.limit=12;render();}if(el.dataset.note&&saved[el.dataset.note])changeSaved(el.dataset.note,{note:el.value});});
  document.addEventListener('change',event=>{const el=event.target;if(el.id==='readiness-filter'){state.readiness=el.value;state.limit=12;render();}if(el.id==='track-filter'){state.track=el.value;state.limit=12;render();}if(el.id==='sort-by'){state.sort=el.value;state.limit=12;updateSortOrder();render();}if(el.dataset.interest&&saved[el.dataset.interest])changeSaved(el.dataset.interest,{interest:el.value});if(el.dataset.compare){if(el.checked){if(comparisons.size>=3){el.checked=false;toast(t('compareLimit'));return;}comparisons.add(el.dataset.compare);}else comparisons.delete(el.dataset.compare);$('#compare-button').textContent=t('compareButton',{n:comparisons.size});$('#compare-button').disabled=comparisons.size<2;}});
  $('#sort-order').addEventListener('click',()=>{state.order=state.order==='desc'?'asc':'desc';state.limit=12;updateSortOrder();render();});
  $('#load-more').addEventListener('click',()=>{const old=state.limit;state.limit+=12;render();$$('.card-title button')[old]?.focus({preventScroll:true});});
  $('#clear-filters').addEventListener('click',reset);$('#detail-dialog').addEventListener('close',closeDetail);
  $$('dialog').forEach(d=>d.addEventListener('click',event=>{if(event.target===d){const r=d.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)d.close();}}));
  document.addEventListener('keydown',event=>{if(event.key==='/'&&!/^(INPUT|TEXTAREA|SELECT)$/.test(document.activeElement?.tagName||'')&&!$('dialog[open]')){event.preventDefault();$('#search').focus();}});
  function openFromHash(){if(!location.hash.startsWith('#idea=')){if($('#detail-dialog').open)$('#detail-dialog').close();return;}try{detail(decodeURIComponent(location.hash.slice(6)),false);}catch{}}
  window.addEventListener('hashchange',openFromHash);
  window.addEventListener('storage',event=>{if(event.key!==storageKey)return;loadSaved(readStore());updateStorageUI();for(const id of ideas.keys())updateSaveButtons(id);if($('#shortlist-dialog').open&&!document.activeElement?.matches('textarea,select'))renderShortlist();});
  loadSaved(readStore());updateStorageUI();renderStatic();render();openFromHash();
})();
